import { useState } from 'react'

import Head from 'next/head'
import Image from 'next/image'

import VolunteerForm from '../components/VolunteerForm'

export default function Home() {
  const [volunteer, setVolunteer] = useState({
    code: 0,
    name: "",
  })

  return (
      <div>
      <Head>
        <title>St. Francis Portal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={""}>
        <h1>Welcome back!</h1>
        
        <VolunteerForm volunteer={volunteer} setVolunteer={setVolunteer}/>
      </div>

      <footer className={""}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={""}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
